/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/pyarrow/pandas_compat.py:742: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
  labels, = index.labels
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/synchronize.py", line 96, in _cleanup
    sem_unlink(name)
FileNotFoundError: [Errno 2] No such file or directory
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:198: UserWarning: semaphore_tracker: There appear to be 34 leaked semaphores to clean up at shutdown
  len(cache))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-fdw_43yb': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-pob8uslg': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-2x5_qa6f': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-sifgiuhh': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-nrugxpvr': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-67o3z5_m': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-78p9hxxq': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-25ygli8e': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-kf46zabm': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-4hc3ezl2': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-bvlv085_': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-3uxoeq4m': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-ovsg65g7': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-w08c4eog': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-f2q60nfj': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-7pkztdt1': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-fpytmmab': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-vgv19eth': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-un4a2wnq': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-d6r2vu7o': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-76498diz': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-o_xi190d': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-x393ahoo': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-iywxgepi': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-easo9kug': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-126dhihu': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-urkn1mfc': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-96sg690d': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-cl2d4mj6': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-9lndrqt5': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-_450p3ei': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-oabfl_e6': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-lh2i_1_o': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
/home/kumarv/willa099/miniconda3/envs/pytorch4/lib/python3.6/site-packages/sklearn/externals/joblib/externals/loky/backend/semaphore_tracker.py:213: UserWarning: semaphore_tracker: '/loky-1182-rw9pc09b': FileNotFoundError(2, 'No such file or directory')
  warnings.warn('semaphore_tracker: %r: %r' % (name, e))
